# Generated by Django 4.2.4 on 2023-08-11 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_rename_user_id_contact_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='username',
            new_name='user_id',
        ),
    ]
